// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using a;

#nullable disable

namespace MIS3033_Exam1_BradenFisher.Migrations
{
    [DbContext(typeof(ExamDB))]
    [Migration("20230927154840_createdbs")]
    partial class createdbs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("a.Patient", b =>
                {
                    b.Property<string>("PID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgeLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("PID");

                    b.ToTable("patTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
